image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay

stages:
  - publish

publish:
  stage: publish
  script:
    - docker build -t $IMAGE_NAME .
    - docker login -u _json_key -p "$GCLOUD_SERVICE_KEY" https://gcr.io
    - docker push gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME
#  only:
#    - master
