steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME', '.' ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME']
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'erp-ui', '--image', 'gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME', '--region', 'europe-west4', '--platform', 'managed', '--allow-unauthenticated']
